### ISSUE TITLE
"Range check error." when opening larger XML conversation files

### ISSUE THREAD

**Issue by theastropath** [LoadLineCalibration/Convedit_Plus#1]
When trying to load M_06-07_HK_Shared.xml or M_10_Mission10.xml I get an error message that says "Range check error.".  Loading the .CON equivalents of those files has no issues.

Both of those missions have a fairly large number of conversations, and the XML file is quite a bit more verbose than the CON file, so I would guess it's related to file size, but you would likely know better

Works well at it's current stage though!

**Comment by LoadLineCalibration** [comment]
Fixed.
