### ISSUE TITLE
"Check labels" bug

### ISSUE THREAD

**Issue by KillerBeer01** [LoadLineCalibration/Convedit_Plus#2]
Apparently, labels in .cons are not case-sensitive, but the "Check labels" function is, so it throws false positives.

Oh, and hi.

**Comment by LoadLineCalibration** [comment]
Hi, 
You mean procedure TfrmMain.VerifyLabels() ?

**Comment by KillerBeer01** [comment]
Not sure what it's called in code, but probably yes.
![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/7059100/b39d9a3f-4b78-46b5-9d4f-5863e4ae223f)

**Comment by LoadLineCalibration** [comment]
Thanks, fixed.
![изображение](https://github.com/LoadLineCalibration/Convedit_Plus/assets/44388228/77543b47-343e-4587-ab4c-7f55f3d9bb72)
