### ISSUE TITLE
Left sidebar doesn't render when running with Wine on Linux

### ISSUE THREAD

**Issue by MQDuck** [LoadLineCalibration/Convedit_Plus#3]
The left sidebar doesn't render when running the program using Wine on Linux, although it seems that it can otherwise be interacted with as normal with the mouse. As far as I can tell, everything else renders fine.

![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/17994307/7e21fb42-501c-4b3b-9a3f-e49cdffee2aa)
![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/17994307/cab313ec-6042-4fef-a950-71cc7413af4d)

**Comment by MQDuck** [comment]
A native Linux build would be really great, if that's an option.

**Comment by LoadLineCalibration** [comment]
[ConEditPlus.zip](https://github.com/LoadLineCalibration/Convedit_Plus/files/14506872/ConEditPlus.zip)
Try this build. 

It is possible to create cross-platform app in Delphi, the problem is that I never had Linux and not familiar with this OS, not to mention creating native programs for it.

**Comment by MQDuck** [comment]
That build doesn't seem any different, unfortunately.

I gather one needs access to Delphi to do a build?

**Comment by MQDuck** [comment]
Something called [CrossKylix](http://crosskylix.untergrund.net/) apparently lets you do Linux builds in Delphi on Windows.

**Comment by LoadLineCalibration** [comment]
Yes, to build from sources, one need Delphi + few extra libs.
I managed to install Linux Mint 21.3 to VM and install Wine. When I find way to transfer files from Windows to Linux VM, I'll try to do something.

**Comment by MQDuck** [comment]
If you're looking to run Windows programs (not just games) on Linux these days, I highly recommend you save yourself a lot of trouble and use [Bottles](https://usebottles.com/).

**Comment by LoadLineCalibration** [comment]
At the moment, the only solution I see is to use Windows VM. The left side is regular TTreeView, there is nothing special. I don't know why Wine cannot handle it.

**Comment by MQDuck** [comment]
If I add this program to Steam as a non-Steam "game" and run it there, it renders correctly. Good enough, I guess.
