### ISSUE TITLE
doesn't play well with high DPI

### ISSUE THREAD

**Issue by Die4Ever** [LoadLineCalibration/Convedit_Plus#4]
![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/30947252/26850f13-d7ab-48b5-9626-74c783940502)

but it does work well when I set the DPI compatibility setting

![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/30947252/7b11aff8-b3af-4db2-acee-d8ef49ab9107)

**Comment by Die4Ever** [comment]
although I still see a slight overlap here, the line number with the label

![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/30947252/044c7cb7-6c50-4ffe-b150-2ef7f9b85cbe)

**Comment by LoadLineCalibration** [comment]
I will see what I can do with this. 

Numbers can be disabled from "View > Show Event Index".

**Comment by LoadLineCalibration** [comment]
The scaling here is 200%
![изображение](https://github.com/LoadLineCalibration/Convedit_Plus/assets/44388228/2afdddec-2ad0-418a-b478-d8ad60b564d9)
I think I have found a way to fix the problem. I'll publish the new release when I fix all event types.

**Comment by LoadLineCalibration** [comment]
Please check the latest version, the problem with events list should be fixed now.

**Comment by Die4Ever** [comment]
it looks great, thank you!
