### ISSUE TITLE
BindNames and Conversation names shown in reverse alphabetical order

### ISSUE THREAD

**Issue by theastropath** [LoadLineCalibration/Convedit_Plus#5]
It appears that the list of names and conversations appears in reverse alphabetical order.  Flags under each conversation look to be in regular alphabetical order.

By comparison, original ConEdit showed the bind names and conversations in regular alphabetical order.

Original:
![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/13684088/e9e087df-fcce-4bb3-a2af-39a28666acad)

ConEditPlus:
![image](https://github.com/LoadLineCalibration/Convedit_Plus/assets/13684088/7c82dd80-23e7-4718-a6b7-257575900179)

**Comment by LoadLineCalibration** [comment]
The tree items are built in the same order as the data in the file. That is, if z comes first, then z will come at the beginning. 

I've added a sorting function call, so from now on, tree items will be sorted in alphabetical order.
![изображение](https://github.com/LoadLineCalibration/Convedit_Plus/assets/44388228/bca65421-cb06-4c33-aedc-eca2cb3c7a86)

**Comment by theastropath** [comment]
Awesome, thanks!

I figured it was something like it being the data order.  Being alphabetical should be a bit more convenient!

**Comment by LoadLineCalibration** [comment]
Beta 6 uses alphabetic tree sorting, closing.
