### ISSUE TITLE
Audio file NOT found

### ISSUE THREAD

**Issue by VeganGreasel** [LoadLineCalibration/Convedit_Plus#6]
Seemingly no matter where I place my audio files, they are never found when I try to play them.

I expect ConEditPlus to look for my file here, but it doesn't seem to:

           ↓ The "Audio Path" in my options
       ┌────────────────────────┐
        C:\DeusEx\MyPackage\Audio\Mission##\OwnerBindName\ConversationName\SpeakerBindName##.mp3

My suggestion is to include the file path in the warning message, maybe in a "details" dropdown. That way we can tell what's going on.

**Comment by LoadLineCalibration** [comment]
You need to point to the correct path in the program options before "Play" will work. 

I did not mention that in the readme. Will fix.

Here is my example: I'm working with GameConversations package sources, located in 
"C:\Games\DeusEx_RTX\GameConversations\". So my path will look like 
"C:\Games\DeusEx_RTX\GameConversations\Audio".
