### ISSUE TITLE
Check flag event: Jump to label doesn't work

### ISSUE THREAD

**Issue by VeganGreasel** [LoadLineCalibration/Convedit_Plus#8]
Version: 2024.4.28.484

1. Create a new conversation
2. Create 2 speech events with individual labels
3. Insert a check flag event above them
4. Pick a flag and a "jump to" label
5. Click update and close the dialog
6. The "jump to" label is now empty

A way to work around it is to save the convo in XML format, edit it manually and open it again.

**EDIT**: That workaround broke my .con file, so don't do that :D

**Comment by LoadLineCalibration** [comment]
Should be fixed in Beta7.
If not, please let me know.
