### ISSUE TITLE
.con files opened in ConEditPlus no longer work in ConEdit

### ISSUE THREAD

**Issue by VeganGreasel** [LoadLineCalibration/Convedit_Plus#9]
I'm aware this is a known issue, but I have a workaround solution using [this tool](https://www.moddb.com/mods/confix/downloads/coneditexport)

To create an XML dump:

```
java -jar ConEditExport.jar -x Mission17.con
```

To restore the XML dump to a CON file:

```
java -jar ConEditExport.jar -c Mission17.xml
```

It might be worth looking into the source code of that tool, or PM the author.

**Comment by LoadLineCalibration** [comment]
There is another workaround. Compile the file, and decompile with DEED 🙂

**Comment by LoadLineCalibration** [comment]
Should be fixed starting from Beta 7.
